all:
  children:
    haproxy:
      hosts:
        haproxy-01:
          ansible_host: 46.16.73.2
          ansible_user: root
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    iis:
      hosts:
        iis-01:
          ansible_host: 217.154.175.26
          ansible_user: Ansible
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985