apiVersion: v1
kind: Secret
metadata:
  name: ssl-automation-secret
  namespace: develop
type: Opaque
stringData:

  GITLAB_TOKEN: "glptt-57dd94a672fa245b9bdbdc59853928b5a2f750fb" # This one is expired and is set for example
  SECRET_KEY: "change-me-to-random-string-1234"
